### ISSUE TITLE
Sending notifications to Android and IOS apps question

### ISSUE THREAD

**Issue by LaloCastilla** [zeyneloz/onesignal-node#10]
We are using this package and it worked very well sending notifications to Android devices. After that, we tried to send notifications to both platforms, Android and IOS using the array method defined in the documentation like this:

```
// create a Client for a multiple apps
var myClient = new OneSignal.Client({
    userAuthKey: 'XXXXXX',
    apps: ['id1Android', 'idIOS'] // your app ids
});
```

It this correct? cause when we try to send notifications to both platforms an error ocurrs but when we try to send it individually it works with the following notation:

```
// create a new Client for a single app
var myClient = new OneSignal.Client({
    userAuthKey: 'XXXXXX',
    // note that "app" must have "appAuthKey" and "appId" keys
    app: { appAuthKey: 'XXXXX', appId: 'XXXXX' }
});
```

**Comment by zeyneloz** [comment]
What is the error you get while sending to the both platforms?
