### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by billel-boudchicha** [zeyneloz/onesignal-node#14]
Hi , i don't think that this is related to your library but i have an issue sending push notifications from my Nodejs server in `Localhost`
when iv sent the first test notification it worked and then it gives me 
```
Something went wrong... { Error: connect ETIMEDOUT 104.16.207.165:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '104.16.207.165',
  port: 443 }
```
Not on a regular basis

thank you

**Comment by zeyneloz** [comment]
You are right, this is not related to the library. The request is getting Timeout error, which means can not connect to the One Signal API server for some reason. There might be several reasons for that, may be you were not connected to the Internet at that moment, maybe you are using a VPN that blocks the traffic or a firewall blocks the Node.js connections on your local computer.
Are you able to view this page in your web browser: https://onesignal.com/api/v1

**Comment by billel-boudchicha** [comment]
I see 404 page which says 
'We searched far and wide, but we couldn't find that page.'
is this what you mean,  is that normal ? thank you

**Comment by iSanjayAchar** [comment]
I'm facing a similar issue

```
Error: connect ETIMEDOUT 104.18.225.52:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: -60,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '104.18.225.52',
  port: 443
}
```

**Comment by thekunalmaheshwari** [comment]
I am also facing the same issue for past few days. on the same server.

**Comment by zeyneloz** [comment]
Please continue on this issue: https://github.com/zeyneloz/onesignal-node/issues/52
