### ISSUE TITLE
Include thread-id in the notification payload

### ISSUE THREAD

**Issue by yusuftor** [zeyneloz/onesignal-node#19]
In order to use grouped notifications on iOS, a `thread-id` parameter has been added ([read more here](https://onesignal.com/blog/ios-12-and-onesignal/)). Please could you implement this! P.S. Not sure if it's thread-id or thread_id ([see docs here](https://documentation.onesignal.com/reference#section-grouping-collapsing))

**Comment by fantapop** [comment]
@yusuftor actually it looks like you would just pass the thread_id through the body of the notification.

**Comment by fantapop** [comment]
I've confirmed this works.  Pass it in as thread_id.  The other appears to be a typo in the onesignal docs.

**Comment by yusuftor** [comment]
Thanks @fantapop, so is it `notification.postBody["thread_id"] = "anidgoeshere"`?

**Comment by fantapop** [comment]
I'm passing it in as part of the initial notification however it looks like adding to the postBody after the notification is created should also work.

I'm doing something like this:
```
        const title = 'my title';
        const body = 'body';
        const threadId = 'thread-id123';
        const notificationParams = {
            ...(title && { headings: { en: title } }),
            ...(threadId && { android_group: threadId, thread_id: threadId }),
            contents: { en: body },
        };
        const notification = new OneSignal.Notification(notificationParams);
```

**Comment by yusuftor** [comment]
Thanks!
