### ISSUE TITLE
viewNotification returns a promise to an object with a data field of string not object

### ISSUE THREAD

**Issue by ozomer** [zeyneloz/onesignal-node#22]
viewNotification returns a promise to an object with a data field of string not object.
We need to use `JSON.parse(...)` to fetch fields `converted`, `successful`, `failed`, etc.

**Comment by zeyneloz** [comment]
`viewNotification` method returns a Promise, you should wait for it to resolve. Then you can parse the response data:

```
myClient.viewNotification('notificationId').then(response => {
  JSON.parse(response.data)
})
```

**Comment by ozomer** [comment]
Why does the client need to call `JSON.parse`? The library should do it automatically.

**Comment by zeyneloz** [comment]
There were reasons at the time this library is written, because of the response structure of the One Signal REST API. I will consider this as a suggestion and add the auto parsing in next version if necessary, thanks.
