### ISSUE TITLE
send_after

### ISSUE THREAD

**Issue by Shruthyshanthraj** [zeyneloz/onesignal-node#23]
Hi,

I am trying to send post notification, But send_after is not working for me. 
I am trying this way-
firstNotification.postBody["send_after"] =
    "Mon Jan 11 2019 15:39:00 GMT-0700 (PDT)";
 myClient.sendNotification(firstNotification, function(
    err,
    httpResponse,
    data
  ) {
    if (err) {
      console.log("Something went wrong...");
    } else {
      console.log('success : '+data);
    }
  });
Can someOne help on this ??

**Comment by dercilima** [comment]
It's easy to resolve!

Your date format is out of formats accepted by OneSignal API.

For more informations, see it -> [Delivery notifications](https://documentation.onesignal.com/reference#section-delivery)
