### ISSUE TITLE
How can I send a push notification to a single player for testing purpose?

### ISSUE THREAD

**Issue by Mustafax06** [zeyneloz/onesignal-node#34]
I see that we can send notifications to segments but I couldn't find a function to send a notification to a specific user. How can I send a notification to a player ID?

**Comment by zeyneloz** [comment]
Please check the [onesignal documentation](https://documentation.onesignal.com/reference#section-send-to-specific-devices)
You can use `include_player_ids` parameter in [.createNotification](https://github.com/zeyneloz/onesignal-node#create-notification) body.
