### ISSUE TITLE
import syntax not working

### ISSUE THREAD

**Issue by kartsims** [zeyneloz/onesignal-node#36]
Hi,

Thanks for the great library! 

I just upgraded from 2.x to 3.0.0 and unfortunately it seems that the `import` syntax is not working anymore.

I am working in Typescript, using `ts-node` to run my script but I suspect this is a global issue.

Please let me know if you need any further information or help testing/debugging on a branch.

Btw it is not a blocker for me since I'll just use the `require` syntax until this issue is solved.

**Comment by klaaz0r** [comment]
Have you tried: `import * as OneSignal from "onesignal-node";`?

**Comment by kartsims** [comment]
Sorry for the late reply. This was actually the issue, I feel stupid but thanks for pointing it out!
