### ISSUE TITLE
the title of the received notification is always "my notification title"

### ISSUE THREAD

**Issue by ahmed-derbalaGMC** [zeyneloz/onesignal-node#45]
with the nodejs module or from the platform website, the notification received is always "my notification title"

`  client.createNotification({
        headings: {
          "en": "bbbbbbbbbbbbb",
          "fr": "eeeeeeeeeee"
        },
        contents: {
          "en": "hhhhhhhhhhhh",
          "fr": "ttttttttttttttt"
        },
        title: {
          "fr": 'textttttttt',
          "en": 'textbbbbbbbbbb'
        },
        subtitle: {
          "fr": 'text13',
          "en": 'tex2222t'
        },
        url: 'http://google.com',
        userIds: ["5e5f78b7cb1bff005fc238d8"]
      })
    .then(response => {
       console.log(response);
    })
    .catch(e => {
      console.log(e);
    });`

**Comment by zeyneloz** [comment]
I didn't find any problems with notification titles on my manual tests. Could you please try with the latest version and open a new issue if the problem continues.
