### ISSUE TITLE
Incorrect Error message type

### ISSUE THREAD

**Issue by Cellule** [zeyneloz/onesignal-node#58]
According to `HTTPError`, the message/body should be a string
https://github.com/zeyneloz/onesignal-node/blob/bd0ae30db2024a4c91e2a726cb51b7671bb9c362/src/errors.ts#L1-L10

However, the body comes from [`request`'s reponse](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3e731478a53999a6ff82abe49f756c1d57debbe5/types/request/index.d.ts#L323) which is not definitely a string.
https://github.com/zeyneloz/onesignal-node/blob/bd0ae30db2024a4c91e2a726cb51b7671bb9c362/src/utils.ts#L54-L57

It can be a string or a buffer or a stream or an object.
![image](https://user-images.githubusercontent.com/4157103/95345446-b9c1ea80-0888-11eb-8f0c-14a0aebaf379.png)

Actually in your case, it is almost always an object (at least for `basicAuthRequest`) because it sends `json: true` in the config
https://github.com/zeyneloz/onesignal-node/blob/bd0ae30db2024a4c91e2a726cb51b7671bb9c362/src/utils.ts#L80-L88

This has lead to many `Error: [object Object]` in our logs making it very hard to understand why the request failed.

You should update the typings to reflect the type of `body` in `HTTPError` and ensure the error message is always a string

**Comment by zeyneloz** [comment]
Thanks for reporting this issue. I merged the fix with this [pull request](https://github.com/zeyneloz/onesignal-node/pull/62) and changes will be released with next version.
