### ISSUE TITLE
Docs: editTagsWithExternalUserIdDevice method name is not correct

### ISSUE THREAD

**Issue by rennehir** [zeyneloz/onesignal-node#60]
In the [docs](https://github.com/zeyneloz/onesignal-node/blob/master/README.md#edit-tags-with-external-user-id) method name `editTagsWithExternalUserId` is used, but it is actually `editTagsWithExternalUserIdDevice` as shown [here](https://github.com/zeyneloz/onesignal-node/blob/bd0ae30db2024a4c91e2a726cb51b7671bb9c362/src/client.ts#L187).

**Comment by zeyneloz** [comment]
Thanks for reporting this typo, I fixed the README file.
