### ISSUE TITLE
All included players are not subscribed 200

### ISSUE THREAD

**Issue by cgw4455** [zeyneloz/onesignal-node#9]
Hi,

thank you for creating this plug-in! Please pardon me if the question is stupid because I am fairly new to coding apps. I've been getting the following error and I was wondering anyone would be so kind to help me out: 

I20180629-12:38:32.129(-4)? { id: '',
I20180629-12:38:32.130(-4)?   recipients: 0,
I20180629-12:38:32.130(-4)?   errors: [ 'All included players are not subscribed' ] } 200

I also checked my users on the onesignal control panel, and I have zero users. Should I subscribe the user differently other than using the code below? In the previous similar issue that's already resolved, I saw that firstNotification.setIncludedSegments(['All']) should be in the code, and I have already done so. 

The code I used are from modified from the onesignal-node github wiki (title: Sending a notification using segments) after putting in my keys and appid:

```
var OneSignal = require('onesignal-node');

// first we need to create a client
var myClient = new OneSignal.Client({
    userAuthKey: 'XXXXXX',
    app: { appAuthKey: 'XXXXX', appId: 'XXXXX' }
});

// we need to create a notification to send
var firstNotification = new OneSignal.Notification({
    contents: {
        en: "Test notification",
        tr: "Test mesajı"
    }
});

// set target users
firstNotification.setIncludedSegments(['All']);
firstNotification.setExcludedSegments(['Inactive Users']);

// set notification parameters
firstNotification.setParameter('data', {"abc": "123", "foo": "bar"});
firstNotification.setParameter('send_after', 'Thu Sep 24 2015 14:00:00 GMT-0700 (PDT)');

// send this notification to All Users except Inactive ones
myClient.sendNotification(firstNotification, function (err, httpResponse,data) {
   if (err) {
       console.log('Something went wrong...');
   } else {
       console.log(data, httpResponse.statusCode);
   }
});
```

The coding language I'm using is Meteor JS 1.6.1. Let me know if you have any questions about my question!

Thank you again!

**Comment by zeyneloz** [comment]
The error message you are getting is from the result of the One Signal API request, which means it is not related to this library so i will close this issue.
I think it is because of this line
`firstNotification.setIncludedSegments(['All']);`
you should change it in to this and remove the following line:
`firstNotification.setIncludedSegments(['Active Users']);`

Check the One Signal documentation for further details:
[https://documentation.onesignal.com/reference#section-send-to-segments](url)
